name: Python package

on:
  push:
    paths:
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install
        run: pip install twine build
      - name: Build
        run: python -m build
      - name: Upload
        env:
          PIP_API_TOKEN: ${{ secrets.PIP_API_TOKEN }}
        run: python -m twine upload dist/* --username __token__ --password ${PIP_API_TOKEN} --skip-existing
